### ISSUE TITLE
Alternative: fakeidentd

### ISSUE THREAD

**Issue by nescafe2002** [flotwig/spoofident#1]
As an alternative, you may use **fakeidentd** as part of the **busybox** container.

Docker:

`docker run --expose 113 busybox fakeidentd -f (string)`

Docker-compose:

```
version: '2'

services:
  app:
    image: busybox:latest
    container_name: fakeidentd
    command: fakeidentd -f (string)
    ports:
      - 113:113/tcp
    network_mode: bridge
    restart: unless-stopped
```
